# Generated by Django 4.2.23 on 2025-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="foreign_key_to_playlist",
            field=models.CharField(
                blank=True,
                default=list,
                help_text="Foreign key to playlist, stored as a string",
                max_length=12,
                null=True,
            ),
        ),
    ]
