# Generated by Django 5.1.1 on 2025-07-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basemodel",
            name="password",
        ),
    ]
