# Generated by Django 4.2.23 on 2025-07-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyUserProfile", "0001_initial"),
        ("user", "0002_alter_basemodel_foreign_key_to_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basemodel",
            name="foreign_key_to_playlist",
        ),
        migrations.AddField(
            model_name="basemodel",
            name="spotify_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to="spotifyUserProfile.spotifyuserprofile",
            ),
        ),
    ]
