# Generated by Django 4.2.23 on 2025-07-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("playlist_url", models.URLField()),
                ("playlist_name", models.CharField(max_length=100)),
                ("playlist_desc", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="playlist_images/"
                    ),
                ),
                ("track_fk_id", models.CharField(blank=True, max_length=50, null=True)),
                ("visibility", models.BooleanField(default=True)),
            ],
        ),
    ]
