# Generated by Django 4.2.23 on 2025-07-04 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("track_url", models.URLField()),
                ("name", models.CharField(max_length=200)),
                ("singer", models.CharField(max_length=100)),
                (
                    "duration",
                    models.DurationField(help_text="Track duration in HH:MM:SS format"),
                ),
                ("image_cover_url", models.URLField(blank=True, null=True)),
                ("in_playlist", models.ManyToManyField(to="playlist.playlist")),
            ],
        ),
    ]
