# Generated by Django 4.2.23 on 2025-07-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyUserProfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="get_track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TrackQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="PlaylistTrack",
            new_name="add_these_tracks",
        ),
        migrations.CreateModel(
            name="Create_Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist_uri",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "spotify_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotifyUserProfile.spotifyuserprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="add_these_tracks",
            name="playlist_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="spotifyUserProfile.create_playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlistimage",
            name="playlist_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="spotifyUserProfile.create_playlist",
            ),
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
