# Generated by Django 4.2.23 on 2025-07-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyUserProfile", "0002_get_track_trackquery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="get_track",
            name="query",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="spotifyUserProfile.trackquery",
            ),
        ),
        migrations.AlterField(
            model_name="add_these_tracks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="get_track",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="playlistimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trackquery",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
