# Generated by Django 4.2.23 on 2025-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spotifyUserProfile",
            "0003_get_track_query_alter_add_these_tracks_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifyuserprofile",
            old_name="spotify_user_id",
            new_name="spotify_id",
        ),
        migrations.RemoveField(
            model_name="spotifyuserprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="spotifyuserprofile",
            name="access_token",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="spotifyuserprofile",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="spotifyuserprofile",
            name="refresh_token",
            field=models.TextField(default=""),
        ),
    ]
