# Generated by Django 4.2.23 on 2025-07-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "user_input",
                    models.TextField(default=list, help_text="User input text"),
                ),
                (
                    "llm_responses",
                    models.JSONField(
                        default=list, help_text="List of LLM response objects"
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user_feedback",
                    models.BooleanField(
                        default=True, help_text="User feedback on the response"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
