# Generated by Django 4.2.23 on 2025-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appresponse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appresponse",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
